dist: xenial
sudo: false

language: node_js
node_js:
  - "10"
  - "12"

env:
  global:
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGOPTIONS='-c client_min_messages=NOTICE'
    - PGPORT=5432
    - POSTGIS_VERSION="2.5"

  matrix:
    - POSTGRESQL_VERSION="10"
    - POSTGRESQL_VERSION="11"
    - POSTGRESQL_VERSION="12"


before_install:
  - sudo service postgresql stop;
  - sudo apt-get remove postgresql* -y
  - sudo apt-get install -y --allow-unauthenticated --no-install-recommends --no-install-suggests postgresql-$POSTGRESQL_VERSION postgresql-client-$POSTGRESQL_VERSION postgresql-server-dev-$POSTGRESQL_VERSION postgresql-common
  - sudo apt-get install -y --allow-unauthenticated postgresql-$POSTGRESQL_VERSION-postgis-$POSTGIS_VERSION postgresql-$POSTGRESQL_VERSION-postgis-$POSTGIS_VERSION-scripts postgis
  - sudo pg_dropcluster --stop $POSTGRESQL_VERSION main
  - sudo rm -rf /etc/postgresql/$POSTGRESQL_VERSION /var/lib/postgresql/$POSTGRESQL_VERSION
  - sudo pg_createcluster -u postgres $POSTGRESQL_VERSION main -- -A trust
  - sudo /etc/init.d/postgresql start $POSTGRESQL_VERSION || sudo journalctl -xe
